fix: web-deploy.yml

diff --git a/.github/workflows/web-deploy.yml b/.github/workflows/web-deploy.yml
--- a/.github/workflows/web-deploy.yml
+++ b/.github/workflows/web-deploy.yml
@@ -27,14 +27,21 @@ jobs:
         run: |
           echo "${{ github.event.client_payload.config_secret }}" | base64 --decode > ./src/config/temp_config.json
 
+      - name: Validate Config JSON
+        run: |
+          if ! jq empty ./src/config/temp_config.json; then
+            echo "Invalid JSON format in temp_config.json"
+            exit 1
+          fi
+
       - name: Set Config Json File
         id: create-json 
         uses: jsdaniell/create-json@v1.2.2 
         with:
-          name: "config.json"
+          name: "config.json"  # 생성할 파일 이름
           json: ${{ steps.decode-config.outputs.result }}
-          dir: './src/config'
-          
+          dir: './src/config'  # 파일이 생성될 디렉토리
+
       - name: Build Project
         working-directory: .
         run: npm run build
